function_names = [
    'ContinueGame',
    'ChkPOffscr',
    'InitChangeSize',
    'NextArea',
    'LRAir',
    'MoveBubl',
    'JCoinC',
    'SPBBox',
    'MoveHammerBroXDir',
    'MoveD_Bowser',
    'BowserGfxHandler',
    'EndAreaPoints',
    'ChkYPCollision',
    'EnemySmackScore',
    'RXSpd',
    'DoEnemySideCheck',
    'GetMaskedOffScrBits',
    'SetupEOffsetFBBox',
    'MoveBoundBoxOffscreen',
    'SprObjectOffscrChk',
    'PlayerGfxProcessing',
    'AnimationControl',
    'GetOffScreenBitsSet',
    'DrawEnemyObject',


    # sound engine stuff
    'LoadEventMusic',
    'LoadAreaMusic',
    'ContinueMusic',
    'SkipSoundSubroutines',

    'PlayBeat',
    'PlayBigJump',
    'PlayBlast',
    'PlayBowserFall',
    'PlayBowserFlame',
    'PlayBrickShatter',
    'PlayBump',
    'PlayCoinGrab',
    'PlayExtraLife',
    'PlayFireballThrow',
    'PlayFlagpoleSlide',
    'PlayGrowPowerUp',
    'PlayGrowVine',
    'PlayNoiseSfx',
    'PlayPipeDownInj',
    'PlayPowerUpGrab',
    'PlaySmackEnemy',
    'PlaySmallJump',
    'PlaySqu1Sfx',
    'PlaySqu2Sfx',
    'PlaySwimStomp',
    'PlayTimerTick',

    'ContinueBlast',
    'ContinueBowserFall',
    'ContinueBowserFlame',
    'ContinueBrickShatter',
    'ContinueBumpThrow',
    'ContinueCGrabTTick',
    'ContinueExtraLife',
    'ContinueGrowItems',
    'ContinueMusic',
    'ContinuePipeDownInj',
    'ContinuePowerUpGrab',
    'ContinueSmackEnemy',
    'ContinueSndJump',
    'ContinueSwimStomp',

    'FindEventMusicHeader',
    'FindAreaMusicHeader',
    'LoadHeader',

    'HandleSquare2Music',
    'HandleSquare1Music',
    'HandleTriangleMusic',
    'HandleNoiseMusic',

    'DecrementSfx2Length',
    'DecrementSfx3Length',
    'Dump_Freq_Regs',
    'HandleAreaMusicLoopB',
]

addrs = [toAddr(x) for x in function_names]

for addr in addrs:
    print('creating {}'.format(addr))
    createFunction(addr, None)
