#ifndef SMBCORE_SMB2JROMARRAYS_H
#define SMBCORE_SMB2JROMARRAYS_H

#define WindFreqEnvData_IntendedLength 24
#define EndOfCastleMusicEnvData_IntendedLength 4
#define AreaMusicEnvData_IntendedLength 8
#define WaterEventMusicEnvData_IntendedLength 40

// The original game modifies an instruction opcode
#define PhysicsInstructionOpcode         RAM(0x80f1)

// The original game modifies an instruction operand
#define PiranhaPlantCompareOperand       RAM(0x9ffe)

// If in World 4+, or the hard worlds
#define PiranhaPlantHardMode (PiranhaPlantCompareOperand != 0x21)

#define GamesBeatenCount                 RAM(0xD29F)

#define VRAM_AddrTable                   RAMARRAY_CONST(0x6060, 62)
#define WorldBits                        RAMARRAY_CONST(0x62F7, 8)
#define FloateyNumTileData               RAMARRAY_CONST(0x63FD, 24)
#define ScoreUpdateData                  RAMARRAY_CONST(0x6415, 12)
#define BackgroundColors                 RAMARRAY_CONST(0x652F, 8)
#define PlayerColors                     RAMARRAY(0x6537, 8)

// GameText aliases some other labels, referenced in by GameTextOffsets
// GameTextOffsets contains 4 entries. WarpZone(Numbers) are referenced explicitly.
#define GameText                         RAMARRAY_CONST(0x6672, 39+31+11+36)
// TopStatusBarLine is mutable because the names are patched in PatchPlayerNamePal
#define TopStatusBarLine                 RAMARRAY(0x6672, 39)

#define WarpZone                         RAMARRAY_CONST(0x66E7, 37)
#define WarpZoneNumbers                  RAMARRAY_CONST(0x670C, 11)
#define GameTextOffsets                  RAMARRAY_CONST(0x6717, 4)

#define ColorRotatePalette               RAMARRAY_CONST(0x68A0, 6)
#define Palette3Data                     RAMARRAY_CONST(0x68AE, 16)
#define BlockGfxData                     RAMARRAY_CONST(0x6916, 20)
#define MetatileGraphics_Low             RAMARRAY_CONST(0x69E5, 4)
#define MetatileGraphics_High            RAMARRAY_CONST(0x69E9, 4)
#define ThankYouMessage                  RAMARRAY(0x6C3D, 20)
#define StatusBarData                    RAMARRAY_CONST(0x6D6D, 8)
#define StatusBarOffset                  RAMARRAY_CONST(0x6D75, 4)
#define DefaultSprOffsets                RAMARRAY_CONST(0x6E2A, 15)
#define MusicSelectData                  RAMARRAY_CONST(0x6F27, 6)

#define HalfwayPageNybbles               RAMARRAY(0x6FFD, 18)
#define BSceneDataOffsets                RAMARRAY_CONST(0x7108, 3)
#define BackSceneryData                  RAMARRAY_CONST(0x710B, 144)
#define BackSceneryMetatiles             RAMARRAY_CONST(0x719B, 36)
#define FSceneDataOffsets                RAMARRAY_CONST(0x71BF, 3)
#define ForeSceneryData                  RAMARRAY_CONST(0x71C2, 39)
#define TerrainMetatiles                 RAMARRAY_CONST(0x71E9, 4)
#define TerrainRenderBits                RAMARRAY_CONST(0x71ED, 32)
#define BlockBuffLowBounds               RAMARRAY_CONST(0x7315, 4)
#define FrenzyIDData                     RAMARRAY_CONST(0x757F, 3)
#define PulleyRopeMetatiles              RAMARRAY_CONST(0x7603, 3)
#define CastleMetatiles                  RAMARRAY_CONST(0x761B, 55)
#define SidePipeShaftData                RAMARRAY_CONST(0x76EB, 4)
#define SidePipeTopPart                  RAMARRAY_CONST(0x76EF, 4)
#define SidePipeBottomPart               RAMARRAY_CONST(0x76F3, 4)
#define VerticalPipeData                 RAMARRAY_CONST(0x7729, 8)
#define CoinMetatileData                 RAMARRAY_CONST(0x7835, 4)
#define C_ObjectRow                      RAMARRAY_CONST(0x7842, 3)
#define C_ObjectMetatile                 RAMARRAY_CONST(0x7845, 3)
#define SolidBlockMetatiles              RAMARRAY_CONST(0x786C, 4)
#define BrickMetatiles                   RAMARRAY_CONST(0x7870, 5)
#define StaircaseHeightData              RAMARRAY_CONST(0x78EC, 9)
#define StaircaseRowData                 RAMARRAY_CONST(0x78F5, 9)
#define HoleMetatiles                    RAMARRAY_CONST(0x7986, 4)
#define ClimbAdderLow                    RAMARRAY_CONST(0x7F33, 4)
#define ClimbAdderHigh                   RAMARRAY_CONST(0x7F37, 4)

#define JumpMForceData                   RAMARRAY(0x7F90, 7)
#define FallMForceData                   RAMARRAY(0x7F97, 7)
#define FrictionData                     RAMARRAY(0x7F9E, 3)

#define PlayerYSpdData                   RAMARRAY_CONST(0x7FA1, 7)
#define InitMForceData                   RAMARRAY_CONST(0x7FA8, 7)
#define MaxLeftXSpdData                  RAMARRAY_CONST(0x7FAF, 3)
#define MaxRightXSpdData                 RAMARRAY_CONST(0x7FB2, 4)
#define Climb_Y_SpeedData                RAMARRAY_CONST(0x7FB6, 3)
#define Climb_Y_MForceData               RAMARRAY_CONST(0x7FB9, 3)
#define PlayerAnimTmrData                RAMARRAY_CONST(0x80F8, 3)

// A total of 4 items. There's a decrement that wraparounds the lookup.
#define FireballXSpdData                 RAMARRAY_CONST(0x81F3, 3)
#define FireballXSpdData_Bug0            RAM_CONST(0x81F3 + 0xFF)

// #define Bubble_MForceData                RAMARRAY_CONST(0x82B7, 2)
// #define BubbleTimerData                  RAMARRAY_CONST(0x82B9, 2)
#define Bubble_MForceData_Bug            RAM_CONST(0x82B7 + 0x6F)
#define BubbleTimerData_Bug              RAM_CONST(0x82B9 + 0x6F)

#define FlagpoleScoreMods                RAMARRAY_CONST(0x83B4, 5)
#define FlagpoleScoreDigits              RAMARRAY_CONST(0x83B9, 5)
#define Jumpspring_Y_PosData             RAMARRAY_CONST(0x842D, 4)
#define HammerEnemyOfsData               RAMARRAY_CONST(0x8654, 9)
#define HammerXSpdData                   RAMARRAY_CONST(0x865D, 2)
#define BrickQBlockMetatiles             RAMARRAY_CONST(0x89B4, 19)
#define LoopCmdWorldNumber               RAMARRAY_CONST(0x8C47, 12)
#define LoopCmdPageNumber                RAMARRAY_CONST(0x8C53, 12)
#define LoopCmdYPosition                 RAMARRAY_CONST(0x8C5F, 12)
#define MultiLoopCount                   RAMARRAY_CONST(0x8C6B, 12)
#define HBroWalkingTimerData             RAMARRAY_CONST(0x8F0A, 2)
#define PRDiffAdjustData                 RAMARRAY_CONST(0x8F83, 12)
#define FirebarSpinSpdData               RAMARRAY_CONST(0x9048, 5)
#define FirebarSpinDirData               RAMARRAY_CONST(0x904D, 5)
#define FlyCCXPositionData               RAMARRAY_CONST(0x9081, 16)
#define FlyCCXSpeedData                  RAMARRAY_CONST(0x9091, 12)
#define FlyCCTimerData                   RAMARRAY_CONST(0x909D, 4)
#define FlameYPosData                    RAMARRAY_CONST(0x91AE, 4)
#define FireworksXPosData                RAMARRAY_CONST(0x9242, 6)
#define FireworksYPosData                RAMARRAY_CONST(0x9248, 6)
#define PlatPosDataLow                   RAMARRAY_CONST(0x94A0, 3)
#define PlatPosDataHigh                  RAMARRAY_CONST(0x94A3, 3)
#define HammerThrowTmrData               RAMARRAY_CONST(0x9603, 2)
#define XSpeedAdderData                  RAMARRAY_CONST(0x9605, 4)
#define RevivedXSpeed                    RAMARRAY_CONST(0x9609, 4)
#define FirebarPosLookupTbl              RAMARRAY_CONST(0x98FC, 99)
#define FirebarMirrorData                RAMARRAY_CONST(0x995F, 4)
#define FirebarTblOffsets                RAMARRAY_CONST(0x9963, 12)

// These two are each length 5 in disassemblies, but they're accessed up to index 15.
// This seems pretty regular.
// They overlap into 6502 instructions.
#define PRandomSubtracter                RAMARRAY_CONST(0x9B0A, 16)
#define FlyCCBPriority                   RAMARRAY_CONST(0x9B0F, 16)

#define LakituDiffAdj                    RAMARRAY_CONST(0x9B5A, 3)
#define BridgeCollapseData               RAMARRAY_CONST(0x9C12, 15)
#define PRandomRange                     RAMARRAY_CONST(0x9C96, 4)
#define FlameTimerData                   RAMARRAY_CONST(0x9E06, 8)
#define StarFlagYPosAdder                RAMARRAY_CONST(0x9F02, 4)
#define StarFlagXPosAdder                RAMARRAY_CONST(0x9F06, 4)
#define StarFlagTileData                 RAMARRAY_CONST(0x9F0A, 4)
#define BowserIdentities                 RAMARRAY_CONST(0xA376, 9)
#define KickedShellPtsData               RAMARRAY_CONST(0xA4EA, 3)
#define StompedEnemyPtsData              RAMARRAY_CONST(0xA5C3, 4)
#define RevivalRateData                  RAMARRAY_CONST(0xA62F, 2)
#define PlayerPosSPlatData               RAMARRAY_CONST(0xA88C, 2)

// Note: These overlap with some instructions and each other. See HandleClimbing().
#define ClimbXPosAdder_Minus1            RAMARRAY_CONST(0xAA96-1, 4)
#define ClimbPLocAdder_Minus1            RAMARRAY_CONST(0xAA98-1, 4)

#define SolidMTileUpperExt               RAMARRAY_CONST(0xAC14, 4)
#define ClimbMTileUpperExt               RAMARRAY_CONST(0xAC1F, 4)
#define EnemyBGCStateData                RAMARRAY_CONST(0xAC42, 6)
#define BoundBoxCtrlData                 RAMARRAY_CONST(0xAE9B, 48)
#define BlockBufferAdderData             RAMARRAY_CONST(0xB04B, 3)
#define BlockBuffer_X_Adder              RAMARRAY_CONST(0xB04E, 28)
#define BlockBuffer_Y_Adder              RAMARRAY_CONST(0xB06A, 28)
#define VineYPosAdder                    RAMARRAY_CONST(0xB0D7, 2)
#define FirstSprXPos                     RAMARRAY_CONST(0xB164, 4)
#define FirstSprYPos                     RAMARRAY_CONST(0xB168, 4)
#define SecondSprXPos                    RAMARRAY_CONST(0xB16C, 4)
#define SecondSprYPos                    RAMARRAY_CONST(0xB170, 4)
#define FirstSprTilenum                  RAMARRAY_CONST(0xB174, 4)
#define SecondSprTilenum                 RAMARRAY_CONST(0xB178, 4)
#define HammerSprAttrib                  RAMARRAY_CONST(0xB17C, 4)
#define FlagpoleScoreNumTiles            RAMARRAY_CONST(0xB1E5, 12)
#define JumpingCoinTiles                 RAMARRAY_CONST(0xB328, 4)
#define PowerUpGfxTable                  RAMARRAY_CONST(0xB364, 20)
#define PowerUpAttributes                RAMARRAY_CONST(0xB378, 5)
#define EnemyGraphicsTable               RAMARRAY_CONST(0xB3ED, 258)
#define EnemyGfxTableOffsets             RAMARRAY_CONST(0xB4EF, 27)
#define EnemyAttributeData               RAMARRAY(0xB50A, 27)
#define DefaultBlockObjTiles             RAMARRAY_CONST(0xB8A8, 4)
#define ExplosionTiles                   RAMARRAY_CONST(0xB9E1, 3)
#define PlayerGfxTblOffsets              RAMARRAY_CONST(0xBAE2, 16)
#define PlayerGraphicsTable              RAMARRAY_CONST(0xBAF2, 208)
#define SwimKickTileNum                  RAMARRAY_CONST(0xBBC2, 2)
#define IntermediatePlayerData           RAMARRAY_CONST(0xBC79, 6)
#define ChangeSizeOffsetAdder            RAMARRAY_CONST(0xBD81, 20)
#define ObjOffsetData                    RAMARRAY_CONST(0xBE8A, 3)
#define XOffscreenBitsData               RAMARRAY_CONST(0xBEC8, 16)
#define DefaultXOnscreenOfs              RAMARRAY_CONST(0xBED8, 3)
#define YOffscreenBitsData               RAMARRAY_CONST(0xBF10, 9)
#define DefaultYOnscreenOfs              RAMARRAY_CONST(0xBF19, 3)
#define FileCount                        RAMARRAY_CONST(0xC0F0, 4)
#define DiskErrorMainMsg                 RAMARRAY(0xC149, 21)
#define DiskErrorMsgOffsets              RAMARRAY_CONST(0xC15E, 4)
#define DiskErrorMsgs                    RAMARRAY_CONST(0xC162, 32)
#define GameOverCursorData               RAMARRAY_CONST(0xC1BD, 3)

#define JumpMForceData_Mario             RAMARRAY_CONST(0xC21F, 7)
#define FallMForceData_Mario             RAMARRAY_CONST(0xC226, 7)
#define FrictionData_Mario               RAMARRAY_CONST(0xC22D, 3)

#define JumpMForceData_Luigi             RAMARRAY_CONST(0xC230, 7)
#define FallMForceData_Luigi             RAMARRAY_CONST(0xC237, 7)
#define FrictionData_Luigi               RAMARRAY_CONST(0xC23E, 3)

#define WorldAddrOffsets                 RAMARRAY_CONST(0xC357, 9)
#define AreaDataOfsLoopback              RAMARRAY_CONST(0xC388, 12)
#define EnemyAddrHOffsets                RAMARRAY_CONST(0xC394, 4)
#define EnemyDataAddrs                   RAMARRAY_CONST(0xC398, 104)
#define AreaDataHOffsets                 RAMARRAY_CONST(0xC400, 4)
#define AreaDataAddrs                    RAMARRAY_CONST(0xC404, 106)
#define MenuCursorTemplate               RAMARRAY(0xC511, 7)
#define MenuCursorTiles                  RAMARRAY_CONST(0xC518, 3)
#define DemoActionData                   RAMARRAY_CONST(0xC530, 17)
#define DemoTimingData                   RAMARRAY_CONST(0xC541, 18)
#define PlayerNameMario                  RAMARRAY_CONST(0xC5EB, 5)
#define PlayerNameLuigi                  RAMARRAY_CONST(0xC5F0, 5)
#define PlayerPaletteMario               RAMARRAY_CONST(0xC5F5, 4)
#define PlayerPaletteLuigi               RAMARRAY_CONST(0xC5F9, 4)
#define TitleScreenGfxData               RAMARRAY(0xC62B, 357)
#define SwimStompEnvelopeData            RAMARRAY_CONST(0xD381, 14)
#define ExtraLifeFreqData                RAMARRAY_CONST(0xD4A4, 6)
#define PowerUpGrabFreqData              RAMARRAY_CONST(0xD4AA, 30)
#define PUp_VGrow_FreqData               RAMARRAY_CONST(0xD4C8, 32)
#define WindFreqEnvData                  RAMARRAY_CONST(0xD5FB, WindFreqEnvData_IntendedLength+1)
#define BrickShatterFreqData             RAMARRAY_CONST(0xD613, 16)
#define SkidSfxFreqData                  RAMARRAY_CONST(0xD623, 6)

#define MusicHeaderData                  RAMARRAY_CONST(0xD949, 0xD9EF - 0xD949)

#define FreqRegLookupTbl                 RAMARRAY_CONST(0xDF00, 102)
#define MusicLengthLookupTbl             RAMARRAY_CONST(0xDF66, 48)

#define EndOfCastleMusicEnvData          RAMARRAY_CONST(0xDF96, EndOfCastleMusicEnvData_IntendedLength+1)
#define AreaMusicEnvData                 RAMARRAY_CONST(0xDF9A, AreaMusicEnvData_IntendedLength+1)
#define WaterEventMusEnvData             RAMARRAY_CONST(0xDFA2, WaterEventMusicEnvData_IntendedLength+1)

#define BowserFlameEnvData_Minus1        RAMARRAY_CONST(0xDFCA-1, 32+1)
#define BrickShatterEnvData              RAMARRAY_CONST(0xDFEA, 16)


#define LeavesYPos                       RAMARRAY(0xC52C, 12)
#define LeavesXPos                       RAMARRAY(0xC538, 12)
#define LeavesTile                       RAMARRAY_CONST(0xC544, 12)
#define LeavesPosAdder                   RAMARRAY_CONST(0xC589, 24)
#define BlueTransPalette                 RAMARRAY_CONST(0xC6A9, 20)
#define BlueTints                        RAMARRAY_CONST(0xC6BD, 4)
#define FlashMRSpriteDataOfs             RAMARRAY_CONST(0xC7A1, 6)
#define MRSpriteDataOfs                  RAMARRAY_CONST(0xC7A7, 7)
#define MRetainerYPos                    RAMARRAY_CONST(0xC7AE, 7)
#define MRetainerXPos                    RAMARRAY_CONST(0xC7B5, 8)
#define EndPlayerName_Mario              RAMARRAY_CONST(0xC84E, 5)
#define EndPlayerName_Luigi              RAMARRAY_CONST(0xC853, 5)
// UNUSED: #define FinalRoomPalette                 RAMARRAY_CONST(0xC87F, 20)
#define ThankYouMessageFinal             RAMARRAY(0xC893, 24)
// UNUSED: #define PeaceIsPavedMsg                  RAMARRAY_CONST(0xC8AB, 22)
// UNUSED: #define WithKingdomSavedMsg              RAMARRAY_CONST(0xC8C1, 22)
#define HurrahMsg                        RAMARRAY(0xC8D7, 20)
// UNUSED: #define OurOnlyHeroMsg                   RAMARRAY_CONST(0xC8EB, 17)
// UNUSED: #define ThisEndsYourTripMsg              RAMARRAY_CONST(0xC8FC, 23)
// UNUSED: #define OfALongFriendshipMsg             RAMARRAY_CONST(0xC913, 24)
// UNUSED: #define PointsAddedMsg                   RAMARRAY_CONST(0xC92B, 24)
// UNUSED: #define ForEachPlayerLeftMsg             RAMARRAY_CONST(0xC943, 25)
// UNUSED: #define PrincessPeachsRoom               RAMARRAY_CONST(0xC95C, 33)
// UNUSED: #define FantasyWorld9Msg                 RAMARRAY_CONST(0xC97D, 67)
// UNUSED: #define SuperPlayerMsg                   RAMARRAY_CONST(0xC9C0, 192)
// UNUSED: #define ModTable1                        RAMARRAY_CONST(0xCF86, 16)
// UNUSED: #define ModTable2                        RAMARRAY_CONST(0xCF96, 16)
// UNUSED: #define MusicHeaderOffsetData            RAMARRAY_CONST(0xCFFA, 11)
// UNUSED: #define AltSound_MusicHeaderData         RAMARRAY_CONST(0xD005, 8)
// UNUSED: #define VictoryPart1BHdr                 RAMARRAY_CONST(0xD00D, 8)
// UNUSED: #define VictoryPart2AHdr                 RAMARRAY_CONST(0xD015, 8)
// UNUSED: #define VictoryPart2CHdr                 RAMARRAY_CONST(0xD01D, 8)
// UNUSED: #define VictoryPart2DHdr                 RAMARRAY_CONST(0xD025, 8)
// UNUSED: #define VictoryPart2BHdr                 RAMARRAY_CONST(0xD02D, 11)
// UNUSED: #define VictoryM_P1AData                 RAMARRAY_CONST(0xD038, 79)
// UNUSED: #define VictoryM_P1BData                 RAMARRAY_CONST(0xD087, 104)
// UNUSED: #define VictoryM_P2AData                 RAMARRAY_CONST(0xD0EF, 23)
// UNUSED: #define VictoryM_P2BData                 RAMARRAY_CONST(0xD106, 61)
// UNUSED: #define VictoryM_P2CData                 RAMARRAY_CONST(0xD143, 104)
// UNUSED: #define VictoryM_P2DData                 RAMARRAY_CONST(0xD1AB, 37)
// UNUSED: #define WaveformData2                    RAMARRAY_CONST(0xD1D0, 32)
// UNUSED: #define VolEnvData2                      RAMARRAY_CONST(0xD1F0, 4)
// UNUSED: #define VolEnvData1                      RAMARRAY_CONST(0xD1F4, 12)
// UNUSED: #define FDSFreqLookupTbl                 RAMARRAY_CONST(0xD200, 60)
// UNUSED: #define VictoryMusEnvData                RAMARRAY_CONST(0xD23C, 16)
// UNUSED: #define WaveformHeaderOffsets            RAMARRAY_CONST(0xD24C, 2)
// UNUSED: #define Wave1Hdr                         RAMARRAY_CONST(0xD24E, 8)
// UNUSED: #define Wave2Hdr                         RAMARRAY_CONST(0xD256, 9)
// UNUSED: #define WaveformData1                    RAMARRAY_CONST(0xD25F, 32)
// UNUSED: #define SweepModData1                    RAMARRAY_CONST(0xD27F, 10)
// UNUSED: #define SweepModData2                    RAMARRAY_CONST(0xD289, 6)
// UNUSED: #define AltSound_MusicLengthLookupTbl    RAMARRAY_CONST(0xD28F, 16)
// UNUSED: #define AltHard_WorldAddrOffsets         RAMARRAY_CONST(0xC357, 9)
#define AltHard_EnemyAddrHOffsets        RAMARRAY_CONST(0xC372, 4)
#define AltHard_EnemyDataAddrs           RAMARRAY_CONST(0xC376, 42)
#define AltHard_AreaDataHOffsets         RAMARRAY_CONST(0xC3A0, 4)
#define AltHard_AreaDataAddrs            RAMARRAY_CONST(0xC3A4, 42)
#define AtoDHalfwayPages                 RAMARRAY_CONST(0xC3CE, 8)


#endif

