#ifndef TILES_H
#define TILES_H

enum metatiles {
  MT_0 = 0,
  MT_BLACK,

  MT_BUSH_L,
  MT_BUSH_M,
  MT_BUSH_R,

  MT_MOUNTAIN_L,
  MT_MOUNTAIN_DOTS_1,
  MT_MOUNTAIN_TOP,
  MT_MOUNTAIN_R,
  MT_MOUNTAIN_DOTS_2,
  MT_MOUNTAIN_GREEN,

  MT_BRIDGE_RAILING,

  MT_BOWSERBRIDGE_CHAIN,
  MT_TREE_TALL_1,
  MT_TREE_SHORT,
  MT_TREE_TALL_2,

  // 10
  MT_PIPE_VERT_WARP_TL,
  MT_PIPE_VERT_WARP_TR,
  MT_PIPE_VERT_DECO_TL,
  MT_PIPE_VERT_DECO_TR,
  MT_PIPE_VERT_UNDER_L,
  MT_PIPE_VERT_UNDER_R,

  // 16
  MT_TREELEDGE_L,
  MT_TREELEDGE_M,
  MT_TREELEDGE_R,

#ifdef SMB1_MODE
  MT_MUSHROOMLEDGE_L,
  MT_MUSHROOMLEDGE_M,
  MT_MUSHROOMLEDGE_R,
#endif

  // 1c/19
  MT_PIPE_SIDEWAYS_TL,
  MT_PIPE_SIDEWAYS_MIDDLE_T,

  // top of connnected pipe (as found at the beginning of 1-2 before Mario goes to underground)
  // 1e/1b
  MT_PIPE_CONNECTED_T,
  MT_PIPE_SIDEWAYS_BL,
  MT_PIPE_SIDEWAYS_MIDDLE_B,
  MT_PIPE_CONNECTED_B,

  // 22/1f
  MT_CORAL,

  MT_SPECIAL_BLOCKHIT,

  MT_FLAGPOLE_T,
  MT_FLAGPOLE_M,

  MT_SPECIAL_VINE,

  // no metatiles from here until 0x40

  MT_ROPE_VERT = 0x40,        // |
  MT_PULLEY_ROPE_HORZ,        // --
  MT_PULLEY_ROPE_TL,          // |-
  MT_PULLEY_ROPE_TR,          // -|
  MT_ROPE_NONE,

  MT_CASTLE_TOP,
  MT_CASTLE_WINDOW_L,
  MT_CASTLE_BRICK,
  MT_CASTLE_WINDOW_R,
  MT_CASTLE_NOTCH,
  MT_CASTLE_DOOR_T,
  MT_CASTLE_DOOR_B,

  MT_TREELEDGE_TRUNK,

  MT_FENCE,
  MT_TREE_TRUNK,

#ifdef SMB1_MODE
  MT_MUSHROOMLEDGE_STEM_T,
  MT_MUSHROOMLEDGE_STEM_UNDER,
#endif

  // MT_BRICK_2 has a white outline on the top
  // 51/4f
  MT_BRICK_2,
  MT_BRICK,
  MT_BRICK_UNUSED,

#ifdef SMB1_MODE
  MT_STONE,
#endif

  // 55/52
  MT_BRICK_2_POWERUP,
#ifdef SMB2J_MODE
  MT_BRICK_2_POISONSHROOM,
#endif
  MT_BRICK_2_VINE,
  MT_BRICK_2_STAR,
  MT_BRICK_2_COINS,
  MT_BRICK_2_1UP,

  // 5a/58
  MT_BRICK_POWERUP,
#ifdef SMB2J_MODE
  MT_BRICK_POISONSHROOM,
#endif
  MT_BRICK_VINE,
  MT_BRICK_STAR,
  MT_BRICK_COINS,
  MT_BRICK_1UP,

  // 5f/5e
  MT_HIDDEN_1COIN,
  MT_HIDDEN_1UP,
#ifdef SMB2J_MODE
  MT_HIDDEN_POISONSHROOM,
  MT_HIDDEN_POWERUP,
#endif

  // 61/62
  MT_STAIR_BLOCK,

  // 62/63
  MT_CASTLE_INSIDE_WALL,
  MT_BRIDGE_BLOCK,

  MT_BULLETBILL_CANNON_T,
  MT_BULLETBILL_CANNON_BODY,
  MT_BULLETBILL_CANNON_B,

  MT_JUMPSPRING_T,
  MT_JUMPSPRING_B,

  // 69/6a
  MT_UNDERWATER_GROUND,
#ifdef SMB2J_MODE
  MT_STONE,
#endif

  MT_unk18,

  // 6b/6d
  MT_WATERPIPE_T,
  MT_WATERPIPE_B,

  // 6d/6f. Might be residual code
  MT_FLAGBALL,

  // no metatiles from here until 0x80

  MT_CLOUD_TL=0x80,
  MT_CLOUD_TM,
  MT_CLOUD_TR,
  MT_CLOUD_BL,
  MT_CLOUD_BM,
  MT_CLOUD_BR,

  MT_WATER_TOP,
  MT_WATER_BLANK,

  MT_CLOUD_BLOCK,
  MT_BOWSERBRIDGE_BLOCK,

#ifdef SMB2J_MODE
  MT_CLOUDLEDGE_L,
  MT_CLOUDLEDGE_M,
  MT_CLOUDLEDGE_R,
#endif

  // 8a/8d
  MT_unk21,

  // no metatiles from here until 0xc0

  MT_QUESTIONBLOCK_COIN = 0xc0,

  MT_QUESTIONBLOCK_POWERUP,
#ifdef SMB2J_MODE
  MT_QUESTIONBLOCK_POISONSHROOM,
#endif

  // c2/c3
  MT_COIN,
  MT_COIN_UNDERWATER,
  MT_BLOCK_EMPTY,   // appears as a used coin block
  MT_AXE,
  MT_unk20
};

static inline bool metatile_is_itemblock(const u8 mt) {
  switch (mt) {
  case MT_QUESTIONBLOCK_POWERUP:
  case MT_QUESTIONBLOCK_COIN:
  case MT_HIDDEN_1COIN:
  case MT_HIDDEN_1UP:
  case MT_BRICK_2_POWERUP:
  case MT_BRICK_2_VINE:
  case MT_BRICK_2_STAR:
  case MT_BRICK_2_COINS:
  case MT_BRICK_2_1UP:
  case MT_BRICK_POWERUP:
  case MT_BRICK_VINE:
  case MT_BRICK_STAR:
  case MT_BRICK_COINS:
  case MT_BRICK_1UP:
    return true;

#ifdef SMB2J_MODE
  case MT_QUESTIONBLOCK_POISONSHROOM:
  case MT_HIDDEN_POISONSHROOM:
  case MT_HIDDEN_POWERUP:
  case MT_BRICK_2_POISONSHROOM:
  case MT_BRICK_POISONSHROOM:
    return true;
#endif

  default:
    return false;
  }
}

enum bgtiles {
  BGTILE_0 = 0, BGTILE_1, BGTILE_2, BGTILE_3, BGTILE_4, BGTILE_5, BGTILE_6, BGTILE_7, BGTILE_8, BGTILE_9,
  BGTILE_A, BGTILE_B, BGTILE_C, BGTILE_D, BGTILE_E, BGTILE_F, BGTILE_G, BGTILE_H, BGTILE_I, BGTILE_J, BGTILE_K, BGTILE_L, BGTILE_M, BGTILE_N, BGTILE_O, BGTILE_P, BGTILE_Q, BGTILE_R, BGTILE_S, BGTILE_T, BGTILE_U, BGTILE_V, BGTILE_W, BGTILE_X, BGTILE_Y, BGTILE_Z,

  // 24
  BGTILE_BLANK_0,
  BGTILE_BLANK_1,
  BGTILE_BLANK_2,
  BGTILE_BLANK_3,
  BGTILE_DASH,
  BGTILE_MULTIPLY,
  BGTILE_BULLETBILL_CANNON_BL,
  BGTILE_EXCLAMATION,
  BGTILE_LEDGE_T1,
  BGTILE_LEDGE_B1,

  BGTILE_STATUS_COIN,

  BGTILE_FLAGPOLE_L,

  // 30
  BGTILE_MOUNTAIN_SLOPE_L,
  BGTILE_MOUNTAIN_PEAK_L,
  BGTILE_MOUNTAIN_PEAK_R,
  BGTILE_MOUNTAIN_SLOPE_R,
  BGTILE_MOUNTAIN_DOTS,

  BGTILE_BUSH_CLOUD_2,
  BGTILE_BUSH_CLOUD_0,
  BGTILE_BUSH_CLOUD_1,
  BGTILE_BUSH_CLOUD_3,
  BGTILE_BUSH_CLOUD_4,
  BGTILE_BUSH_CLOUD_5,
  BGTILE_BUSH_CLOUD_6,
  BGTILE_BUSH_CLOUD_7,

  BGTILE_FLAGPOLE_R,
 
  BGTILE_PULLEY_TL,
  BGTILE_PULLEY_BL,
  BGTILE_BULLETBILL_CANNON_BR,
  BGTILE_WATER_LAVA,
  BGTILE__0x42,
  BGTILE__0x43,
  BGTILE__0x44,
  BGTILE_BRICK_T,
  BGTILE__0x46,
  BGTILE_BRICK,
  BGTILE__0x48,
  BGTILE__0x49,
  BGTILE__0x4a,

  BGTILE_TREELEDGE_TL,
  BGTILE_TREELEDGE_BL,
  BGTILE_TREELEDGE_TM,
  BGTILE_TREELEDGE_BM0,
  BGTILE_TREELEDGE_BM1,
  BGTILE_TREELEDGE_TR,
  BGTILE_TREELEDGE_BR,
  BGTILE_TREELEDGE_TRUNK,

  BGTILE_QUESTIONBLOCK_TL,
  BGTILE_QUESTIONBLOCK_TR,
  BGTILE_QUESTIONBLOCK_BL,
  BGTILE_QUESTIONBLOCK_BR,
  BGTILE_BLOCK_EMPTY_TL,
  BGTILE_BLOCK_EMPTY_TR,
  BGTILE_BLOCK_EMPTY_BL,
  BGTILE_BLOCK_EMPTY_BR,
  BGTILE_PULLEY_TR,
  BGTILE_PULLEY_BR,
  BGTILE_CASTLE_INSIDE_WALL_T,
  BGTILE_CASTLE_INSIDE_WALL_B,
  BGTILE__0x5f,

  BGTILE_PIPE_VERT_T0,
  BGTILE_PIPE_VERT_T1,
  BGTILE_PIPE_VERT_T2,
  BGTILE_PIPE_VERT_T3,
  BGTILE_PIPE_VERT_B0,
  BGTILE_PIPE_VERT_B1,
  BGTILE_PIPE_VERT_B2,
  BGTILE_PIPE_VERT_B3,
  BGTILE_PIPE_VERT_SHAFT_L,
  BGTILE_PIPE_VERT_SHAFT_M,
  BGTILE_PIPE_VERT_SHAFT_R,

  BGTILE_LEDGE_T0,
  BGTILE_LEDGE_T2,
  BGTILE_LEDGE_T3,
  BGTILE_LEDGE_T4,
  BGTILE_LEDGE_T5,
  BGTILE_LEDGE_B0,
  BGTILE_LEDGE_B2,
  BGTILE_LEDGE_B3,
  BGTILE_LEDGE_B4,
  BGTILE_LEDGE_B5,
  BGTILE_LEDGE_STEM_TL,
  BGTILE_LEDGE_STEM_TR,

  BGTILE_BOWSERBRIDGE_T,
  BGTILE__0x78,
  BGTILE_BOWSERBRIDGE_B,

  BGTILE__0x7a,

  BGTILE_AXE_TL,
  BGTILE_AXE_TR,
  BGTILE_AXE_BL,
  BGTILE_AXE_BR,
  BGTILE_BOWSERBRIDGE_CHAIN,

  BGTILE_FENCE_TL,
  BGTILE_FENCE_TR,
  BGTILE_UNDERWATER_GROUND_TL,
  BGTILE_UNDERWATER_GROUND_BL,
  BGTILE_UNDERWATER_GROUND_TR,
  BGTILE_UNDERWATER_GROUND_BR,
  // 86
  BGTILE_PIPE_SIDEWAYS_0,
  BGTILE_PIPE_SIDEWAYS_1,
  BGTILE_PIPE_SIDEWAYS_2,
  BGTILE_PIPE_SIDEWAYS_3,
  BGTILE_PIPE_SIDEWAYS_4,
  BGTILE_PIPE_SIDEWAYS_5,
  BGTILE_PIPE_SIDEWAYS_6,
  BGTILE_PIPE_SIDEWAYS_7,
  BGTILE_PIPE_SIDEWAYS_8,
  BGTILE_PIPE_SIDEWAYS_9,
  BGTILE_PIPE_SIDEWAYS_A,
  BGTILE_PIPE_SIDEWAYS_B,
  BGTILE_PIPE_SIDEWAYS_C,
  BGTILE_PIPE_SIDEWAYS_D,
  BGTILE_PIPE_SIDEWAYS_E,
  BGTILE_PIPE_SIDEWAYS_F,
  BGTILE__0x96,
  BGTILE__0x97,
  BGTILE__0x98,
  BGTILE_PULLEY_ROPE_HORZ,
  BGTILE__0x9a,
  BGTILE_CASTLE_DOOR_TL,
  BGTILE_CASTLE_DOOR_TR,
  BGTILE_CASTLE_TOP_L,
  BGTILE_CASTLE_TOP_R,
  BGTILE__0x9f,

  // A0
  BGTILE_FENCE_BL,
  BGTILE_FENCE_BR,
  BGTILE_FLAGPOLE_ROPE_L,
  BGTILE_FLAGPOLE_ROPE_R,
  BGTILE_CORAL_0,

  BGTILE_COIN_TL,
  BGTILE_COIN_TR,
  BGTILE_COIN_BL,
  BGTILE_COIN_BR,

  BGTILE_CASTLE_NOTCH_L,
  BGTILE_CASTLE_NOTCH_R,

  BGTILE_STAIR_BLOCK_TL,
  BGTILE_STAIR_BLOCK_BL,
  BGTILE_STAIR_BLOCK_TR,
  BGTILE_STAIR_BLOCK_BR,

  BGTILE__0xaf,

  BGTILE_CLOUD_BLOCK_TL,
  BGTILE_CLOUD_BLOCK_BL,
  BGTILE_CLOUD_BLOCK_TR,
  BGTILE_CLOUD_BLOCK_BR,

  BGTILE_STONE_TL,
  BGTILE_STONE_TR,
  BGTILE_STONE_BL,
  BGTILE_STONE_BR,

  BGTILE_TREE_TL,
  BGTILE_TREE_TR,
  BGTILE_TREE_L,
  BGTILE_TREE_R,
  BGTILE_TREE_BL,
  BGTILE_TREE_BR,
  BGTILE_TREE_TRUNK_L,
  BGTILE_TREE_TRUNK_R,

  BGTILE_BRIDGE_RAILING,
  BGTILE_BRIDGE_BLOCK,

  BGTILE_COIN_UNDERWATER_TL,
  BGTILE_COIN_UNDERWATER_TR,
  BGTILE_COIN_UNDERWATER_BL,
  BGTILE_COIN_UNDERWATER_BR,

  BGTILE_BULLETBILL_CANNON_0,
  BGTILE_BULLETBILL_CANNON_1,
  BGTILE_BULLETBILL_CANNON_2,
  BGTILE_BULLETBILL_CANNON_3,
  BGTILE_BULLETBILL_CANNON_4,
  BGTILE_BULLETBILL_CANNON_5,
  BGTILE_BULLETBILL_CANNON_6,
  BGTILE_BULLETBILL_CANNON_7,

  BGTILE_MUSHROOM_ICON,
  BGTILE_COPYRIGHT,
  BGTILE__0xd0,
  BGTILE__0xd1,
  BGTILE__0xd2,
  BGTILE__0xd3,
  BGTILE__0xd4,
  BGTILE__0xd5,
  BGTILE__0xd6,
  BGTILE__0xd7,
  BGTILE__0xd8,
  BGTILE__0xd9,
  BGTILE__0xda,
  BGTILE__0xdb,
  BGTILE__0xdc,
  BGTILE__0xdd,
  BGTILE__0xde,
  BGTILE__0xdf,
  BGTILE__0xe0,
  BGTILE__0xe1,
  BGTILE__0xe2,
  BGTILE__0xe3,
  BGTILE__0xe4,
  BGTILE__0xe5,
  BGTILE__0xe6,
  BGTILE__0xe7,
  BGTILE__0xe8,
  BGTILE_CORAL_1,
  BGTILE_CORAL_2,
  BGTILE_CORAL_3,
  BGTILE__0xec,
  BGTILE__0xed,
  BGTILE__0xee,
  BGTILE__0xef,
  BGTILE__0xf0,
  BGTILE__0xf1,
  BGTILE__0xf2,
  BGTILE__0xf3,
  BGTILE__0xf4,
  BGTILE__0xf5,
  BGTILE__0xf6,
  BGTILE__0xf7,
  BGTILE__0xf8,
  BGTILE__0xf9,
  BGTILE__0xfa,
  BGTILE__0xfb,
  BGTILE__0xfc,
  BGTILE__0xfd,
  BGTILE__0xfe,
  BGTILE__0xff,
};

enum spritetiles {
  STILE_PLAYER__0x00 = 0x00,
  STILE_PLAYER__0x01,
  STILE_PLAYER__0x02,
  STILE_PLAYER__0x03,
  STILE_PLAYER__0x04,
  STILE_PLAYER__0x05,
  STILE_PLAYER__0x06,
  STILE_PLAYER__0x07,
  STILE_PLAYER__0x08,
  STILE_PLAYER__0x09,
  STILE_PLAYER__0x0a,
  STILE_PLAYER__0x0b,
  STILE_PLAYER__0x0c,
  STILE_PLAYER__0x0d,
  STILE_PLAYER__0x0e,
  STILE_PLAYER__0x0f,
  STILE_PLAYER__0x10,
  STILE_PLAYER__0x11,
  STILE_PLAYER__0x12,
  STILE_PLAYER__0x13,
  STILE_PLAYER__0x14,
  STILE_PLAYER__0x15,
  STILE_PLAYER__0x16,
  STILE_PLAYER__0x17,
  STILE_PLAYER__0x18,
  STILE_PLAYER__0x19,
  STILE_PLAYER__0x1a,
  STILE_PLAYER__0x1b,
  STILE_PLAYER__0x1c,
  STILE_PLAYER__0x1d,
  STILE_PLAYER__0x1e,
  STILE_PLAYER__0x1f,
  STILE_PLAYER__0x20,
  STILE_PLAYER__0x21,
  STILE_PLAYER__0x22,
  STILE_PLAYER__0x23,
  STILE_PLAYER__0x24,
  STILE_PLAYER__0x25,
  STILE_PLAYER__0x26,
  STILE_PLAYER__0x27,
  STILE_PLAYER__0x28,
  STILE_PLAYER__0x29,
  STILE_PLAYER__0x2a,
  STILE_PLAYER__0x2b,
  STILE_PLAYER__0x2c,
  STILE_PLAYER__0x2d,
  STILE_PLAYER__0x2e,
  STILE_PLAYER__0x2f,
  STILE_PLAYER__0x30,
  STILE_PLAYER__0x31,
  STILE_PLAYER__0x32,
  STILE_PLAYER__0x33,
  STILE_PLAYER__0x34,
  STILE_PLAYER__0x35,
  STILE_PLAYER__0x36,
  STILE_PLAYER__0x37,
  STILE_PLAYER__0x38,
  STILE_PLAYER__0x39,
  STILE_PLAYER__0x3a,
  STILE_PLAYER__0x3b,
  STILE_PLAYER__0x3c,
  STILE_PLAYER__0x3d,
  STILE_PLAYER__0x3e,
  STILE_PLAYER__0x3f,
  STILE_PLAYER__0x40,
  STILE_PLAYER__0x41,
  STILE_PLAYER__0x42,
  STILE_PLAYER__0x43,
  STILE_PLAYER__0x44,
  STILE_PLAYER__0x45,
  STILE_PLAYER__0x46,
  STILE_PLAYER__0x47,
  STILE_PLAYER__0x48,
  STILE_PLAYER__0x49,
  STILE_PLAYER__0x4a,
  STILE_PLAYER__0x4b,
  STILE_PLAYER__0x4c,
  STILE_PLAYER__0x4d,
  STILE_PLAYER__0x4e,
  STILE_PLAYER__0x4f,

  STILE_SCORE_00,

  STILE_BOWSER_FLAME_0,
  STILE_BOWSER_FLAME_1,
  STILE_BOWSER_FLAME_2,

  STILE_FLAG_TL,
  STILE_FLAG_TR,
  STILE_FLAG_BL,
  STILE_FLAG_BR,

  STILE_PLAYER__0x58,
  STILE_PLAYER__0x59,
  STILE_PLAYER__0x5a,

  STILE_PLATFORM,

  STILE_PLAYER__0x5c,
  STILE_PLAYER__0x5d,
  STILE_PLAYER__0x5e,
  STILE_PLAYER__0x5f,

  STILE_JUMPING_COIN_0,
  STILE_JUMPING_COIN_1,
  STILE_JUMPING_COIN_2,
  STILE_JUMPING_COIN_3,

  STILE_FIREBALL_0,
  STILE_FIREBALL_1,

  STILE_EXPLOSION_2,
  STILE_EXPLOSION_1,
  STILE_EXPLOSION_0,

  STILE_BUBBLE = 0x74,
  STILE_BALL,

#ifdef SMB1_MODE
  STILE_MUSHROOM_TL,
  STILE_MUSHROOM_TR,
  STILE_MUSHROOM_BL,
  STILE_MUSHROOM_BR,
#endif

#ifdef SMB2J_MODE
  STILE_LEAF_0 = 0x7a,
  STILE_LEAF_1,
#endif

  STILE_FLAGPOLE_FLAG_TRIANGLE = 0x7e,
  STILE_FLAGPOLE_FLAG_SKULL,

  STILE_HAMMER_HEAD = 0x80,
  STILE_HAMMER_HANDLE,
  STILE_HAMMER_HEAD_ROTATED,
  STILE_HAMMER_HANDLE_ROTATED,

  STILE_BRICK_CHUNK,
  STILE_BRICK_T,
  STILE_BRICK,

  STILE_BLOCK_EMPTY,

  STILE_STAR_T = 0x8d,

  STILE_PLAYER__0x90 = 0x90,
  STILE_PLAYER__0x91,
  STILE_PLAYER__0x92,
  STILE_PLAYER__0x93,

  STILE_PLAYER__0x9e = 0x9e,
  STILE_PLAYER__0x9f,

  STILE_FIREFLOWER_T = 0xd6,
  STILE_FIREFLOWER_B = 0xd9,

#ifdef SMB2J_MODE
  STILE_MUSHROOM_TL = 0xd8,
  STILE_MUSHROOM_TR = 0xda,
  STILE_MUSHROOM_BL,
#endif

  STILE_VINE_T = 0xe0,
  STILE_VINE,

  STILE_STAR_B = 0xe4,

  STILE_SCORE_10 = 0xf6,
  STILE_SCORE_20,
  STILE_SCORE_40,
  STILE_SCORE_50,
  STILE_SCORE_80,
  STILE_SCORE_0,

  STILE_BLANK,

  STILE_SCORE_1UP_0,
  STILE_SCORE_1UP_1,

#ifdef SMB1_MODE
  STILE_SPRITE0TEST = 0xff
#endif
#ifdef SMB2J_MODE
  STILE_MUSHROOM_BR = 0xff
#endif

};

#endif

